# Main Navigation Menu

[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Our Products"
url = "/products/"
weight = 2

[[main]]
name = "Our Story Yet"
url = "/about/"
weight = 3

[[main]]
name = "Whats Going On"
url = "/blog/"
weight = 4

[[main]]
name = "Reach Us 24x7"
url = "/contact/"
weight = 5
